### ISSUE TITLE
console.save in android

### ISSUE THREAD

**Issue by delijati** [bgrins/devtools-snippets#60]
how to download the created file into desktop instead of downloading to android?

**Comment by bgrins** [comment]
Oh that's interesting that it saves in android, but I guess it makes sense based on https://github.com/bgrins/devtools-snippets/blob/master/snippets/console-save/console-save.js#L16-L24.  I'm not sure how to make the download happen in the desktop but in this case you could use the copy helper in the console like `copy(obj)` then save it to a file.
